spring:
  datasource:
    #sqlite 默认数据库
    sqlite:
      jdbc-url: jdbc:sqlite::resource:config/data
      driver-class-name: org.sqlite.JDBC
    #mariadb 默认连接配置
    mariadb:
      password: xxx
      username: xxx
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://host:port/xxxx?characterEncoding=UTF-8
    #oracle 默认连接配置
    oracle:
      password: xxx
      username: xxx
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@host:port/xxx